# Generated by Django 2.0.2 on 2018-02-24 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('book_description', models.TextField(max_length=500)),
                ('book_price', models.IntegerField()),
                ('date_created', models.DateField(verbose_name=datetime.datetime(2018, 2, 24, 20, 30, 12, 83761))),
            ],
        ),
    ]
