# Generated by Django 2.0.2 on 2018-02-25 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180225_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2018, 2, 25, 9, 29, 33, 386490)),
        ),
    ]
