# Generated by Django 2.0.2 on 2018-02-25 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180225_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2018, 2, 25, 11, 52, 39, 238305)),
        ),
    ]
