# Generated by Django 2.0.2 on 2018-02-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_item',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
