# Generated by Django 2.0.2 on 2018-02-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180226_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.IntegerField(),
        ),
    ]
