# Generated by Django 2.0.2 on 2018-02-27 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180227_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_user_id', models.IntegerField()),
                ('date_placed', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_items', models.CharField(max_length=255)),
            ],
        ),
    ]
