# Generated by Django 2.0.2 on 2018-02-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_created',
        ),
    ]
