# Generated by Django 2.0.2 on 2018-03-01 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_book_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 12, 51, 39, 903465, tzinfo=utc)),
        ),
    ]
