# Generated by Django 2.0.2 on 2018-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180301_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
