name: CI
on:
  push:
    branches: [main]
jobs: 
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - run: |
          mkdir -p logs/
          echo 'Environment/App/db' > logs/exclude.txt
      
      
      - uses: max/secret-scan@master
        with:
          exclude_path: 'logs/exclude.txt'

                

